spring.application.name=user-service
server.port=9511

spring.datasource.url=jdbc:postgresql://localhost:5434/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
auth.service.url=http://localhost:12717/api/auth
jwt.secret=9H6zJ6tXr0qv8J2Lr9+N3sYwGJ6gkA8v5Xq7mT+0O1Q=
