spring.application.name=auth-service
server.port=9510

spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9H6zJ6tXr0qv8J2Lr9+N3sYwGJ6gkA8v5Xq7mT+0O1Q=
jwt.access-token-validity-minutes=15
jwt.refresh-token-validity-minutes=10080

spring.jackson.default-property-inclusion=non_null
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer