version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--save", "900", "1",
      "--save", "300", "10",
      "--save", "60", "10000",
      "--maxmemory-policy", "allkeys-lru",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    ports:
      - "6370:6379"
    environment:
      - REDIS_PASSWORD=root
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
